# Generated by Django 3.2.8 on 2021-10-25 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20211022_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 12, 56, 7, 147562, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
